/**
 * Canonical city lists for the bulk geocoder (scripts/build-cities.ts).
 *
 * `region` is the disambiguator the geocoder scopes by: a US state for ATS, a
 * country for ETS2. Names are the common English spellings; if WoT scrapes a
 * different spelling/accent for a city you actually drive to, the on-demand
 * backfill during sync will geocode that exact name and the curated cityCoords.ts
 * can override anything that lands wrong. So this list just pre-warms the map —
 * it doesn't need to be perfect or exhaustive.
 *
 * ATS = base + released map DLC states. ETS2 = base + map DLC countries.
 */
export interface CitySeed {
	city: string;
	region: string;
}

export const ATS_CITIES: CitySeed[] = [
	// California
	{ city: 'Bakersfield', region: 'California' },
	{ city: 'Barstow', region: 'California' },
	{ city: 'Carlsbad', region: 'California' },
	{ city: 'El Centro', region: 'California' },
	{ city: 'Eureka', region: 'California' },
	{ city: 'Fresno', region: 'California' },
	{ city: 'Huron', region: 'California' },
	{ city: 'Los Angeles', region: 'California' },
	{ city: 'Oakdale', region: 'California' },
	{ city: 'Oxnard', region: 'California' },
	{ city: 'Redding', region: 'California' },
	{ city: 'Sacramento', region: 'California' },
	{ city: 'San Diego', region: 'California' },
	{ city: 'San Francisco', region: 'California' },
	{ city: 'San Rafael', region: 'California' },
	{ city: 'Santa Cruz', region: 'California' },
	{ city: 'Santa Maria', region: 'California' },
	{ city: 'Stockton', region: 'California' },
	{ city: 'Truckee', region: 'California' },
	{ city: 'Ukiah', region: 'California' },
	// Nevada
	{ city: 'Carson City', region: 'Nevada' },
	{ city: 'Elko', region: 'Nevada' },
	{ city: 'Ely', region: 'Nevada' },
	{ city: 'Las Vegas', region: 'Nevada' },
	{ city: 'Pioche', region: 'Nevada' },
	{ city: 'Primm', region: 'Nevada' },
	{ city: 'Reno', region: 'Nevada' },
	{ city: 'Tonopah', region: 'Nevada' },
	{ city: 'Winnemucca', region: 'Nevada' },
	// Arizona
	{ city: 'Camp Verde', region: 'Arizona' },
	{ city: 'Flagstaff', region: 'Arizona' },
	{ city: 'Grand Canyon Village', region: 'Arizona' },
	{ city: 'Kayenta', region: 'Arizona' },
	{ city: 'Kingman', region: 'Arizona' },
	{ city: 'Nogales', region: 'Arizona' },
	{ city: 'Page', region: 'Arizona' },
	{ city: 'Phoenix', region: 'Arizona' },
	{ city: 'San Simon', region: 'Arizona' },
	{ city: 'Show Low', region: 'Arizona' },
	{ city: 'Sierra Vista', region: 'Arizona' },
	{ city: 'Tucson', region: 'Arizona' },
	{ city: 'Yuma', region: 'Arizona' },
	// New Mexico
	{ city: 'Alamogordo', region: 'New Mexico' },
	{ city: 'Albuquerque', region: 'New Mexico' },
	{ city: 'Carlsbad', region: 'New Mexico' },
	{ city: 'Clovis', region: 'New Mexico' },
	{ city: 'Farmington', region: 'New Mexico' },
	{ city: 'Gallup', region: 'New Mexico' },
	{ city: 'Hobbs', region: 'New Mexico' },
	{ city: 'Las Cruces', region: 'New Mexico' },
	{ city: 'Roswell', region: 'New Mexico' },
	{ city: 'Santa Fe', region: 'New Mexico' },
	{ city: 'Socorro', region: 'New Mexico' },
	{ city: 'Tucumcari', region: 'New Mexico' },
	// Oregon
	{ city: 'Astoria', region: 'Oregon' },
	{ city: 'Bend', region: 'Oregon' },
	{ city: 'Burns', region: 'Oregon' },
	{ city: 'Coos Bay', region: 'Oregon' },
	{ city: 'Eugene', region: 'Oregon' },
	{ city: 'Klamath Falls', region: 'Oregon' },
	{ city: 'Medford', region: 'Oregon' },
	{ city: 'Newport', region: 'Oregon' },
	{ city: 'Ontario', region: 'Oregon' },
	{ city: 'Pendleton', region: 'Oregon' },
	{ city: 'Portland', region: 'Oregon' },
	{ city: 'Salem', region: 'Oregon' },
	{ city: 'The Dalles', region: 'Oregon' },
	// Washington
	{ city: 'Aberdeen', region: 'Washington' },
	{ city: 'Bellingham', region: 'Washington' },
	{ city: 'Colville', region: 'Washington' },
	{ city: 'Ellensburg', region: 'Washington' },
	{ city: 'Everett', region: 'Washington' },
	{ city: 'Grand Coulee', region: 'Washington' },
	{ city: 'Kennewick', region: 'Washington' },
	{ city: 'Longview', region: 'Washington' },
	{ city: 'Olympia', region: 'Washington' },
	{ city: 'Omak', region: 'Washington' },
	{ city: 'Port Angeles', region: 'Washington' },
	{ city: 'Seattle', region: 'Washington' },
	{ city: 'Spokane', region: 'Washington' },
	{ city: 'Tacoma', region: 'Washington' },
	{ city: 'Vancouver', region: 'Washington' },
	{ city: 'Wenatchee', region: 'Washington' },
	{ city: 'Yakima', region: 'Washington' },
	// Utah
	{ city: 'Blanding', region: 'Utah' },
	{ city: 'Cedar City', region: 'Utah' },
	{ city: 'Logan', region: 'Utah' },
	{ city: 'Moab', region: 'Utah' },
	{ city: 'Ogden', region: 'Utah' },
	{ city: 'Price', region: 'Utah' },
	{ city: 'Provo', region: 'Utah' },
	{ city: 'Salina', region: 'Utah' },
	{ city: 'Salt Lake City', region: 'Utah' },
	{ city: 'St. George', region: 'Utah' },
	{ city: 'Vernal', region: 'Utah' },
	// Idaho
	{ city: 'Boise', region: 'Idaho' },
	{ city: 'Coeur d’Alene', region: 'Idaho' },
	{ city: 'Idaho Falls', region: 'Idaho' },
	{ city: 'Ketchum', region: 'Idaho' },
	{ city: 'Lewiston', region: 'Idaho' },
	{ city: 'Nampa', region: 'Idaho' },
	{ city: 'Pocatello', region: 'Idaho' },
	{ city: 'Salmon', region: 'Idaho' },
	{ city: 'Twin Falls', region: 'Idaho' },
	// Colorado
	{ city: 'Alamosa', region: 'Colorado' },
	{ city: 'Burlington', region: 'Colorado' },
	{ city: 'Colorado Springs', region: 'Colorado' },
	{ city: 'Craig', region: 'Colorado' },
	{ city: 'Denver', region: 'Colorado' },
	{ city: 'Durango', region: 'Colorado' },
	{ city: 'Fort Collins', region: 'Colorado' },
	{ city: 'Grand Junction', region: 'Colorado' },
	{ city: 'Lamar', region: 'Colorado' },
	{ city: 'Montrose', region: 'Colorado' },
	{ city: 'Pueblo', region: 'Colorado' },
	{ city: 'Sterling', region: 'Colorado' },
	// Wyoming
	{ city: 'Casper', region: 'Wyoming' },
	{ city: 'Cheyenne', region: 'Wyoming' },
	{ city: 'Cody', region: 'Wyoming' },
	{ city: 'Gillette', region: 'Wyoming' },
	{ city: 'Jackson', region: 'Wyoming' },
	{ city: 'Laramie', region: 'Wyoming' },
	{ city: 'Rawlins', region: 'Wyoming' },
	{ city: 'Rock Springs', region: 'Wyoming' },
	{ city: 'Sheridan', region: 'Wyoming' },
	// Montana
	{ city: 'Billings', region: 'Montana' },
	{ city: 'Bozeman', region: 'Montana' },
	{ city: 'Butte', region: 'Montana' },
	{ city: 'Great Falls', region: 'Montana' },
	{ city: 'Havre', region: 'Montana' },
	{ city: 'Helena', region: 'Montana' },
	{ city: 'Kalispell', region: 'Montana' },
	{ city: 'Miles City', region: 'Montana' },
	{ city: 'Missoula', region: 'Montana' },
	// Texas
	{ city: 'Amarillo', region: 'Texas' },
	{ city: 'Austin', region: 'Texas' },
	{ city: 'Dallas', region: 'Texas' },
	{ city: 'El Paso', region: 'Texas' },
	{ city: 'Fort Worth', region: 'Texas' },
	{ city: 'Galveston', region: 'Texas' },
	{ city: 'Houston', region: 'Texas' },
	{ city: 'Laredo', region: 'Texas' },
	{ city: 'Lubbock', region: 'Texas' },
	{ city: 'Lufkin', region: 'Texas' },
	{ city: 'Odessa', region: 'Texas' },
	{ city: 'San Antonio', region: 'Texas' },
	{ city: 'Victoria', region: 'Texas' },
	// Oklahoma
	{ city: 'Clinton', region: 'Oklahoma' },
	{ city: 'Enid', region: 'Oklahoma' },
	{ city: 'Guymon', region: 'Oklahoma' },
	{ city: 'Lawton', region: 'Oklahoma' },
	{ city: 'McAlester', region: 'Oklahoma' },
	{ city: 'Oklahoma City', region: 'Oklahoma' },
	{ city: 'Tulsa', region: 'Oklahoma' },
	{ city: 'Woodward', region: 'Oklahoma' },
	// Kansas
	{ city: 'Dodge City', region: 'Kansas' },
	{ city: 'Garden City', region: 'Kansas' },
	{ city: 'Hays', region: 'Kansas' },
	{ city: 'Liberal', region: 'Kansas' },
	{ city: 'Salina', region: 'Kansas' },
	{ city: 'Topeka', region: 'Kansas' },
	{ city: 'Wichita', region: 'Kansas' },
	// Nebraska
	{ city: 'Grand Island', region: 'Nebraska' },
	{ city: 'Lincoln', region: 'Nebraska' },
	{ city: 'North Platte', region: 'Nebraska' },
	{ city: 'Omaha', region: 'Nebraska' },
	{ city: 'Scottsbluff', region: 'Nebraska' },
	// Arkansas
	{ city: 'El Dorado', region: 'Arkansas' },
	{ city: 'Fort Smith', region: 'Arkansas' },
	{ city: 'Hot Springs', region: 'Arkansas' },
	{ city: 'Jonesboro', region: 'Arkansas' },
	{ city: 'Little Rock', region: 'Arkansas' },
	{ city: 'Pine Bluff', region: 'Arkansas' },
	{ city: 'Texarkana', region: 'Arkansas' },
	// Missouri
	{ city: 'Cape Girardeau', region: 'Missouri' },
	{ city: 'Joplin', region: 'Missouri' },
	{ city: 'Kansas City', region: 'Missouri' },
	{ city: 'Springfield', region: 'Missouri' },
	{ city: 'St. Louis', region: 'Missouri' }
];

export const ETS2_CITIES: CitySeed[] = [
	// Germany
	{ city: 'Berlin', region: 'Germany' },
	{ city: 'Bremen', region: 'Germany' },
	{ city: 'Dortmund', region: 'Germany' },
	{ city: 'Dresden', region: 'Germany' },
	{ city: 'Duisburg', region: 'Germany' },
	{ city: 'Düsseldorf', region: 'Germany' },
	{ city: 'Erfurt', region: 'Germany' },
	{ city: 'Frankfurt am Main', region: 'Germany' },
	{ city: 'Hamburg', region: 'Germany' },
	{ city: 'Hannover', region: 'Germany' },
	{ city: 'Kassel', region: 'Germany' },
	{ city: 'Kiel', region: 'Germany' },
	{ city: 'Köln', region: 'Germany' },
	{ city: 'Leipzig', region: 'Germany' },
	{ city: 'Magdeburg', region: 'Germany' },
	{ city: 'Mannheim', region: 'Germany' },
	{ city: 'München', region: 'Germany' },
	{ city: 'Nürnberg', region: 'Germany' },
	{ city: 'Osnabrück', region: 'Germany' },
	{ city: 'Rostock', region: 'Germany' },
	{ city: 'Stuttgart', region: 'Germany' },
	{ city: 'Travemünde', region: 'Germany' },
	// Austria
	{ city: 'Graz', region: 'Austria' },
	{ city: 'Innsbruck', region: 'Austria' },
	{ city: 'Klagenfurt', region: 'Austria' },
	{ city: 'Linz', region: 'Austria' },
	{ city: 'Salzburg', region: 'Austria' },
	{ city: 'Wien', region: 'Austria' },
	// Belgium
	{ city: 'Brussel', region: 'Belgium' },
	{ city: 'Liège', region: 'Belgium' },
	// Netherlands
	{ city: 'Amsterdam', region: 'Netherlands' },
	{ city: 'Groningen', region: 'Netherlands' },
	{ city: 'Rotterdam', region: 'Netherlands' },
	// Luxembourg
	{ city: 'Luxembourg', region: 'Luxembourg' },
	// France
	{ city: 'Ajaccio', region: 'France' },
	{ city: 'Bastia', region: 'France' },
	{ city: 'Bordeaux', region: 'France' },
	{ city: 'Bourges', region: 'France' },
	{ city: 'Brest', region: 'France' },
	{ city: 'Calais', region: 'France' },
	{ city: 'Clermont-Ferrand', region: 'France' },
	{ city: 'Dijon', region: 'France' },
	{ city: 'Le Havre', region: 'France' },
	{ city: 'Le Mans', region: 'France' },
	{ city: 'Lille', region: 'France' },
	{ city: 'Limoges', region: 'France' },
	{ city: 'Lyon', region: 'France' },
	{ city: 'Marseille', region: 'France' },
	{ city: 'Metz', region: 'France' },
	{ city: 'Montpellier', region: 'France' },
	{ city: 'Nantes', region: 'France' },
	{ city: 'Nice', region: 'France' },
	{ city: 'Paris', region: 'France' },
	{ city: 'Reims', region: 'France' },
	{ city: 'Rennes', region: 'France' },
	{ city: 'Strasbourg', region: 'France' },
	{ city: 'Toulouse', region: 'France' },
	// United Kingdom
	{ city: 'Aberdeen', region: 'United Kingdom' },
	{ city: 'Birmingham', region: 'United Kingdom' },
	{ city: 'Cambridge', region: 'United Kingdom' },
	{ city: 'Cardiff', region: 'United Kingdom' },
	{ city: 'Carlisle', region: 'United Kingdom' },
	{ city: 'Dover', region: 'United Kingdom' },
	{ city: 'Edinburgh', region: 'United Kingdom' },
	{ city: 'Glasgow', region: 'United Kingdom' },
	{ city: 'Grimsby', region: 'United Kingdom' },
	{ city: 'Liverpool', region: 'United Kingdom' },
	{ city: 'London', region: 'United Kingdom' },
	{ city: 'Manchester', region: 'United Kingdom' },
	{ city: 'Newcastle-upon-Tyne', region: 'United Kingdom' },
	{ city: 'Plymouth', region: 'United Kingdom' },
	{ city: 'Sheffield', region: 'United Kingdom' },
	{ city: 'Southampton', region: 'United Kingdom' },
	{ city: 'Swansea', region: 'United Kingdom' },
	// Italy
	{ city: 'Ancona', region: 'Italy' },
	{ city: 'Bari', region: 'Italy' },
	{ city: 'Bologna', region: 'Italy' },
	{ city: 'Cagliari', region: 'Italy' },
	{ city: 'Catania', region: 'Italy' },
	{ city: 'Firenze', region: 'Italy' },
	{ city: 'Genova', region: 'Italy' },
	{ city: 'Messina', region: 'Italy' },
	{ city: 'Milano', region: 'Italy' },
	{ city: 'Napoli', region: 'Italy' },
	{ city: 'Palermo', region: 'Italy' },
	{ city: 'Pescara', region: 'Italy' },
	{ city: 'Roma', region: 'Italy' },
	{ city: 'Taranto', region: 'Italy' },
	{ city: 'Torino', region: 'Italy' },
	{ city: 'Venezia', region: 'Italy' },
	{ city: 'Verona', region: 'Italy' },
	// Switzerland
	{ city: 'Bern', region: 'Switzerland' },
	{ city: 'Genève', region: 'Switzerland' },
	{ city: 'Zürich', region: 'Switzerland' },
	// Czechia
	{ city: 'Brno', region: 'Czechia' },
	{ city: 'Ostrava', region: 'Czechia' },
	{ city: 'Plzeň', region: 'Czechia' },
	{ city: 'Praha', region: 'Czechia' },
	// Poland
	{ city: 'Gdańsk', region: 'Poland' },
	{ city: 'Katowice', region: 'Poland' },
	{ city: 'Kraków', region: 'Poland' },
	{ city: 'Łódź', region: 'Poland' },
	{ city: 'Poznań', region: 'Poland' },
	{ city: 'Szczecin', region: 'Poland' },
	{ city: 'Warszawa', region: 'Poland' },
	{ city: 'Wrocław', region: 'Poland' },
	// Slovakia
	{ city: 'Bratislava', region: 'Slovakia' },
	{ city: 'Košice', region: 'Slovakia' },
	// Hungary
	{ city: 'Budapest', region: 'Hungary' },
	{ city: 'Debrecen', region: 'Hungary' },
	{ city: 'Pécs', region: 'Hungary' },
	// Scandinavia
	{ city: 'København', region: 'Denmark' },
	{ city: 'Odense', region: 'Denmark' },
	{ city: 'Aalborg', region: 'Denmark' },
	{ city: 'Frederikshavn', region: 'Denmark' },
	{ city: 'Esbjerg', region: 'Denmark' },
	{ city: 'Göteborg', region: 'Sweden' },
	{ city: 'Helsingborg', region: 'Sweden' },
	{ city: 'Kalmar', region: 'Sweden' },
	{ city: 'Malmö', region: 'Sweden' },
	{ city: 'Stockholm', region: 'Sweden' },
	{ city: 'Uppsala', region: 'Sweden' },
	{ city: 'Växjö', region: 'Sweden' },
	{ city: 'Bergen', region: 'Norway' },
	{ city: 'Kristiansand', region: 'Norway' },
	{ city: 'Oslo', region: 'Norway' },
	{ city: 'Stavanger', region: 'Norway' },
	{ city: 'Trondheim', region: 'Norway' },
	// Iberia
	{ city: 'A Coruña', region: 'Spain' },
	{ city: 'Barcelona', region: 'Spain' },
	{ city: 'Bilbao', region: 'Spain' },
	{ city: 'Madrid', region: 'Spain' },
	{ city: 'Málaga', region: 'Spain' },
	{ city: 'Sevilla', region: 'Spain' },
	{ city: 'Valencia', region: 'Spain' },
	{ city: 'Zaragoza', region: 'Spain' },
	{ city: 'Lisboa', region: 'Portugal' },
	{ city: 'Porto', region: 'Portugal' },
	{ city: 'Faro', region: 'Portugal' }
];

export const ALL_SEEDS: { game: 'ets2' | 'ats'; seeds: CitySeed[] }[] = [
	{ game: 'ats', seeds: ATS_CITIES },
	{ game: 'ets2', seeds: ETS2_CITIES }
];
